package com.sober.demo.dao.generatedMapper;

import com.sober.demo.dao.dto.SoberTest;
import com.sober.demo.dao.dto.SoberTestExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SoberTestMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sober_test
     *
     * @mbggenerated
     */
    int countByExample(SoberTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sober_test
     *
     * @mbggenerated
     */
    int deleteByExample(SoberTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sober_test
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sober_test
     *
     * @mbggenerated
     */
    int insert(SoberTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sober_test
     *
     * @mbggenerated
     */
    int insertSelective(SoberTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sober_test
     *
     * @mbggenerated
     */
    List<SoberTest> selectByExample(SoberTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sober_test
     *
     * @mbggenerated
     */
    SoberTest selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sober_test
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") SoberTest record, @Param("example") SoberTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sober_test
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") SoberTest record, @Param("example") SoberTestExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sober_test
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(SoberTest record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sober_test
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(SoberTest record);
}